import pytest
import numpy as np
import math as m
import os
import copy
import json
import pickle

import satkit as sk
from shared import ISS_2021, ISS_NAME, STARLINK_3118


class TestTLE:
    def test_tle_setting(self):
        """
        Test setting TLE parameters
        """
        tle = sk.TLE.from_lines(ISS_2021)[0]
        assert tle.inclination == pytest.approx(51.6432, rel=1e-7)
        assert tle.raan == pytest.approx(351.4697, rel=1e-7)
        assert tle.eccen == pytest.approx(0.0007417, rel=1e-7)
        assert tle.arg_of_perigee == pytest.approx(130.5364, rel=1e-7)
        assert tle.mean_anomaly == pytest.approx(329.6482, rel=1e-7)
        assert tle.mean_motion == pytest.approx(15.48915330, rel=1e-7)
        assert tle.bstar == pytest.approx(0.00010270, rel=1e-4)
        assert abs((tle.epoch - sk.time(2021, 10, 2, 14, 10, 59.0)).seconds) < 1

        tle.raan = 50.0
        assert tle.raan == pytest.approx(50.0, rel=1e-7)
        tle.eccen = 0.1
        assert tle.eccen == pytest.approx(0.1, rel=1e-7)
        tle.arg_of_perigee = 40.0
        assert tle.arg_of_perigee == pytest.approx(40.0, rel=1e-7)
        tle.mean_anomaly = 300.0
        assert tle.mean_anomaly == pytest.approx(300.0, rel=1e-7)
        tle.mean_motion = 14.0
        assert tle.mean_motion == pytest.approx(14.0, rel=1e-7)
        tle.bstar = 0.0002
        assert tle.bstar == pytest.approx(0.0002, rel=1e-4)


    def test_tle_pickle(self):
        """TLE pickle must round-trip every serialized field."""
        tle = sk.TLE.from_lines([ISS_NAME, *ISS_2021])[0]

        restored = pickle.loads(pickle.dumps(tle))

        assert restored.name == tle.name
        assert restored.satnum == tle.satnum
        assert restored.inclination == pytest.approx(tle.inclination, rel=1e-12)
        assert restored.raan == pytest.approx(tle.raan, rel=1e-12)
        assert restored.eccen == pytest.approx(tle.eccen, rel=1e-12)
        assert restored.arg_of_perigee == pytest.approx(tle.arg_of_perigee, rel=1e-12)
        assert restored.mean_anomaly == pytest.approx(tle.mean_anomaly, rel=1e-12)
        assert restored.mean_motion == pytest.approx(tle.mean_motion, rel=1e-12)
        assert restored.bstar == pytest.approx(tle.bstar, rel=1e-12)
        assert abs((restored.epoch - tle.epoch).seconds) < 1e-6
        # The restored TLE must propagate identically
        t = tle.epoch + sk.duration.from_hours(1.0)
        p1, v1 = sk.sgp4(tle, t)
        p2, v2 = sk.sgp4(restored, t)
        assert np.allclose(p1, p2) and np.allclose(v1, v2)

    def test_tle_pickle_rejects_garbage(self):
        """Malformed / pre-versioned pickle bytes raise ValueError, not a panic."""
        tle = sk.TLE.__new__(sk.TLE)
        with pytest.raises(ValueError):
            tle.__setstate__(b"aaaa")
        # A wrong version byte gets the explicit unsupported-version message
        with pytest.raises(ValueError, match="version"):
            tle.__setstate__(bytes([7] * 200))


class TestTLEFitting:
    def test_tle_fit(self):
        """
        Test fitting of TLE From high-precision states
        """
        altitude = 400e3
        r0 = sk.consts.earth_radius + altitude
        v0 = m.sqrt(sk.consts.mu_earth / r0)
        inc = 97 * m.pi / 180
        state0 = np.array([r0, 0, 0, 0, v0 * m.cos(inc), v0 * m.sin(inc)])

        sp = sk.satproperties(cdaoverm=2.0 * 10 / 3500)
        tm = sk.time(2016, 5, 16, 12, 0, 0)
        res = sk.propagate(
            state0, tm, end=tm + sk.duration.from_days(1), satproperties=sp
        )
        time_arr = [tm + sk.duration(seconds=x * 10) for x in range(8640)]
        state_arr = [res.interp(t) for t in time_arr]
        epoch = time_arr[0]

        _tle, result = sk.TLE.fit_from_states(state_arr, time_arr, epoch)  # type: ignore
        # tlefitstatus.converged is a property (a state flag), not a method
        status = result["status"]
        assert isinstance(status.converged, bool)
        assert status.converged == result["converged"]

    @pytest.mark.parametrize("gravconst", [None, sk.sgp4_gravconst.wgs84])
    def test_fit_recovers_sgp4_states(self, gravconst):
        """States generated by SGP4 are reproduced by the fitted TLE when the
        fit uses the same gravity model (default WGS72, as sgp4) and the exact
        TEME rotation; before 0.24 the fit used WGS84."""
        kw = {} if gravconst is None else {"gravconst": gravconst}
        tle = sk.TLE.from_lines(ISS_2021)[0]
        times = [tle.epoch + sk.duration(minutes=10 * i) for i in range(145)]
        pteme, vteme = sk.sgp4(tle, times, **kw)
        states = []
        for t, p, v in zip(times, pteme, vteme):
            q = sk.frametransform.rotation(sk.frame.TEME, sk.frame.GCRF, t)
            states.append(np.concatenate([q * p, q * v]))
        fit, result = sk.TLE.fit_from_states(states, times, tle.epoch, **kw)  # type: ignore
        assert result["converged"]
        pfit, _ = sk.sgp4(fit, times, **kw)
        assert np.max(np.linalg.norm(pfit - pteme, axis=1)) < 0.05
        assert fit.inclination == pytest.approx(tle.inclination, abs=1e-6)

    def test_fit_kwargs_are_keyword_only(self):
        tle = sk.TLE.from_lines(ISS_2021)[0]
        with pytest.raises(TypeError):
            sk.TLE.fit_from_states([], [], tle.epoch, sk.sgp4_gravconst.wgs72)  # type: ignore[misc]
        with pytest.raises(ValueError, match="gravconst"):
            sk.TLE.fit_from_states([], [], tle.epoch, gravconst="wgs72")  # type: ignore[arg-type]


class TestSGP4:
    def test_to_lines(self):
        """
        Test converting TLE to lines
        """

        lines = ["STARLINK-3118", *STARLINK_3118]
        tle = sk.TLE.from_lines(lines)[0]

        lines2 = tle.to_2line()
        assert lines[1:] == lines2

        lines2 = tle.to_3line()
        assert lines == lines2

    def test_to_2line_satnum_too_large_raises_value_error(self):
        """A catalog number above the Alpha-5 range (339999) cannot be
        written to a TLE; ``to_2line`` should raise ``ValueError`` (a bad
        input value), not the generic ``RuntimeError`` other TLE formatting
        failures raise."""
        lines = ["STARLINK-3118", *STARLINK_3118]
        tle = sk.TLE.from_lines(lines)[0]
        tle.satnum = 340000
        with pytest.raises(ValueError, match="OMM"):
            tle.to_2line()

    def test_omm(self, testvec_dir):
        """
        Test propagation of Orbital Mean-Element Message (OMM)
        which is represented as a dictionary
        """

        basedir = testvec_dir + os.path.sep + "omm" + os.path.sep

        # Plain json.load output is accepted as-is
        with open(basedir + "spacetrack_omm.json", "r") as fh:
            omm_list = json.load(fh)
        epoch = sk.time(omm_list[0]["EPOCH"])
        _p, _v = sk.sgp4(omm_list[0], epoch)
        p_list, _v = sk.sgp4(omm_list[0:3], epoch)
        assert p_list.shape == (3, 3)

        with open(basedir + "celestrak_omm.json", "r") as fh:
            omm_list = json.load(fh)
        epoch = sk.time(omm_list[0]["EPOCH"])
        _p, _v = sk.sgp4(omm_list[0], epoch)
        _p, _v = sk.sgp4(omm_list[0:3], epoch)

    def test_omm_loaders(self, testvec_dir):
        """
        omm_from_file / omm_from_text: JSON and XML, Space-Track and CelesTrak,
        must give the same dictionaries, with every field and extra kept
        """
        basedir = testvec_dir + os.path.sep + "omm" + os.path.sep

        st_json = sk.omm_from_file(basedir + "spacetrack_omm.json")
        st_xml = sk.omm_from_file(basedir + "spacetrack_omm.xml")
        assert len(st_json) == len(st_xml) == 2000
        j, x = st_json[0], st_xml[0]
        # Space-Track quotes every number; the loader returns numbers
        assert isinstance(j["MEAN_MOTION"], float)
        assert isinstance(j["NORAD_CAT_ID"], int)
        assert isinstance(x["MEAN_MOTION"], float)
        # Metadata, comments and user-defined extras all survive both formats
        for key in ("CCSDS_OMM_VERS", "COMMENT", "ORIGINATOR", "CREATION_DATE",
                    "TIME_SYSTEM", "MEAN_ELEMENT_THEORY", "OBJECT_TYPE",
                    "SEMIMAJOR_AXIS", "RCS_SIZE", "GP_ID"):
            assert j[key] == x[key], key
        assert j["RCS_SIZE"] is None
        # The JSON endpoint also carries the TLE lines; XML does not
        assert set(j) - set(x) == {"TLE_LINE0", "TLE_LINE1", "TLE_LINE2"}
        assert set(x) <= set(j)
        for key in x:
            assert x[key] == j[key], key

        ct_json = sk.omm_from_file(basedir + "celestrak_omm.json")
        ct_xml = sk.omm_from_file(basedir + "celestrak_omm.xml")
        assert len(ct_json) == len(ct_xml) == 149
        assert ct_json[0]["OBJECT_NAME"] == ct_xml[0]["OBJECT_NAME"]
        assert ct_json[0]["MEAN_MOTION"] == ct_xml[0]["MEAN_MOTION"]

        # Loaded dicts propagate; a JSON re-serialization round-trips
        epoch = sk.time(j["EPOCH"])
        p1, _v = sk.sgp4(j, epoch)
        p2, _v = sk.sgp4(x, epoch)
        p3, _v = sk.sgp4(sk.omm_from_text(json.dumps(j))[0], epoch)
        assert np.array_equal(p1, p2)
        assert np.array_equal(p1, p3)

        # A bare JSON object (not an array) is accepted too
        assert len(sk.omm_from_text(json.dumps(j))) == 1
        # KVN is not
        with pytest.raises(RuntimeError, match="KVN"):
            sk.omm_from_text("CCSDS_OMM_VERS = 3.0")

    def test_omm_matches_tle_lines(self, testvec_dir):
        """
        Space-Track ships the TLE lines with each OMM: both parsers must
        give the same SGP4 state (to the TLE's 0.864 ms epoch resolution)
        """
        basedir = testvec_dir + os.path.sep + "omm" + os.path.sep
        omms = sk.omm_from_file(basedir + "spacetrack_omm.json")
        checked = 0
        for rec in omms[:100]:
            tle = sk.TLE.from_lines([rec["TLE_LINE1"], rec["TLE_LINE2"]])[0]
            tm = sk.time(rec["EPOCH"]) + sk.duration(hours=3)
            p_tle, _v, e_tle = sk.sgp4(tle, tm, errflag=True)
            p_omm, _v, e_omm = sk.sgp4(rec, tm, errflag=True)
            if e_tle[0] != 0 or e_omm[0] != 0:
                continue
            assert np.linalg.norm(p_tle - p_omm) < 10.0, rec["OBJECT_NAME"]
            checked += 1
        assert checked > 50

    def test_omm_dict_shapes(self):
        """
        sgp4 accepts flat CCSDS dicts and the nested groups of an
        xmltodict-style tree, with numbers as strings, and rejects what
        SGP4 cannot propagate
        """
        flat = {
            "OBJECT_NAME": "ISS (ZARYA)", "OBJECT_ID": "1998-067A",
            "EPOCH": "2021-10-02T14:10:59.999", "TIME_SYSTEM": "UTC",
            "MEAN_ELEMENT_THEORY": "SGP4",
            "MEAN_MOTION": "15.48915330", "ECCENTRICITY": "0.0007417",
            "INCLINATION": "51.6432", "RA_OF_ASC_NODE": "351.4697",
            "ARG_OF_PERICENTER": "130.5364", "MEAN_ANOMALY": "329.6482",
            "BSTAR": "0.0001027", "MEAN_MOTION_DOT": "0.00016717",
            "MEAN_MOTION_DDOT": "0",
        }
        epoch = sk.time(flat["EPOCH"])
        tm = epoch + sk.duration(minutes=30)
        p_ref, _v = sk.sgp4(flat, tm)

        # Nested (xmltodict) form, handed in at the omm, body, or data level
        nested = {
            "@id": "CCSDS_OMM_VERS", "@version": "2.0",
            "body": {"segment": {
                "metadata": {k: flat[k] for k in ("OBJECT_NAME", "OBJECT_ID",
                                                  "TIME_SYSTEM", "MEAN_ELEMENT_THEORY")},
                "data": {
                    "meanElements": {k: flat[k] for k in (
                        "EPOCH", "MEAN_MOTION", "ECCENTRICITY", "INCLINATION",
                        "RA_OF_ASC_NODE", "ARG_OF_PERICENTER", "MEAN_ANOMALY")},
                    "tleParameters": {k: flat[k] for k in (
                        "BSTAR", "MEAN_MOTION_DOT", "MEAN_MOTION_DDOT")},
                    "userDefinedParameters": {"USER_DEFINED": [
                        {"@parameter": "OBJECT_TYPE", "#text": "PAYLOAD"},
                        {"@parameter": "RCS_SIZE"},
                    ]},
                },
            }},
        }
        for node in (nested, nested["body"], nested["body"]["segment"]["data"]):
            p, _v = sk.sgp4(node, tm)
            assert np.array_equal(p, p_ref)

        # A trimmed dict with only the elements, epoch as satkit.time / datetime
        minimal = {k: float(flat[k]) for k in (
            "MEAN_MOTION", "ECCENTRICITY", "INCLINATION", "RA_OF_ASC_NODE",
            "ARG_OF_PERICENTER", "MEAN_ANOMALY")}
        minimal["BSTAR"] = float(flat["BSTAR"])
        minimal["MEAN_MOTION_DOT"] = float(flat["MEAN_MOTION_DOT"])
        for ep in (epoch, epoch.to_datetime(), flat["EPOCH"]):
            p, _v = sk.sgp4({**minimal, "EPOCH": ep}, tm)
            assert np.linalg.norm(p - p_ref) < 1e-6

        # Optional fields may be None or empty; metadata is case-insensitive
        p, _v = sk.sgp4({**flat, "BSTAR": None, "MEAN_MOTION_DDOT": "",
                         "MEAN_ELEMENT_THEORY": " sgp4 "}, tm)
        assert np.linalg.norm(p - p_ref) < 1e3  # BSTAR gone: small drag change

        with pytest.raises(RuntimeError, match="EPOCH"):
            sk.sgp4({}, tm)
        with pytest.raises(RuntimeError, match="MEAN_MOTION"):
            sk.sgp4({**flat, "MEAN_MOTION": "fast"}, tm)
        with pytest.raises(RuntimeError, match="EPHEMERIS_TYPE 4"):
            sk.sgp4({**flat, "EPHEMERIS_TYPE": 4}, tm)
        with pytest.raises(RuntimeError, match="MEAN_ELEMENT_THEORY"):
            sk.sgp4({**flat, "MEAN_ELEMENT_THEORY": "DSST"}, tm)
        with pytest.raises(RuntimeError, match="TIME_SYSTEM"):
            sk.sgp4({**flat, "TIME_SYSTEM": "TAI"}, tm)
        # Elements in another frame or about another body are refused too
        with pytest.raises(RuntimeError, match="REF_FRAME"):
            sk.sgp4({**flat, "REF_FRAME": "GCRF"}, tm)
        with pytest.raises(RuntimeError, match="CENTER_NAME"):
            sk.sgp4({**flat, "CENTER_NAME": "MOON"}, tm)
        p, _v = sk.sgp4({**flat, "REF_FRAME": "TEME", "CENTER_NAME": "earth"}, tm)
        assert np.array_equal(p, p_ref)

        # The CCSDS day-of-year epoch form (2021-275 is 2 October)
        p, _v = sk.sgp4({**flat, "EPOCH": "2021-275T14:10:59.999"}, tm)
        assert np.array_equal(p, p_ref)
        assert sk.TLE.from_omm({**flat, "EPOCH": "2021-275T14:10:59.999Z"}).epoch == epoch

    def test_tle_omm_conversion(self):
        """
        TLE.to_omm / TLE.from_omm round-trip and agree with sgp4 on both
        """
        tle = sk.TLE.from_lines([ISS_NAME, *ISS_2021])[0]

        omm = tle.to_omm()
        assert omm["OBJECT_NAME"] == "ISS (ZARYA)"
        assert omm["OBJECT_ID"] == "1998-067A"
        assert omm["NORAD_CAT_ID"] == 25544
        assert omm["ELEMENT_SET_NO"] == 900
        assert omm["REV_AT_EPOCH"] == 29935
        assert omm["EPHEMERIS_TYPE"] == 0
        assert omm["MEAN_ELEMENT_THEORY"] == "SGP4"
        assert omm["MEAN_MOTION"] == tle.mean_motion
        assert omm["BSTAR"] == tle.bstar
        assert sk.time(omm["EPOCH"]) == tle.epoch
        assert "CLASSIFICATION_TYPE" not in omm
        json.dumps(omm)  # plain JSON-serializable values only

        back = sk.TLE.from_omm(omm)
        assert back.to_2line() == tle.to_2line()
        assert back.intl_desig == "98067A"
        assert back.name == "ISS (ZARYA)"

        tm = tle.epoch + sk.duration(hours=1)
        p_tle, v_tle = sk.sgp4(tle, tm)
        p_omm, v_omm = sk.sgp4(omm, tm)
        p_back, v_back = sk.sgp4(back, tm)
        assert np.array_equal(p_tle, p_omm)
        assert np.array_equal(p_tle, p_back)

        # Pickling the converted TLE keeps the designator
        assert pickle.loads(pickle.dumps(back)).intl_desig == "98067A"

    def test_sgp4_vallado(self, testvec_dir):
        """
        SGP4 Test Vectors from vallado
        """

        basedir = testvec_dir + os.path.sep + "sgp4"

        tlefile = basedir + os.path.sep + "SGP4-VER.TLE"
        with open(tlefile, "r") as fh:
            lines = fh.readlines()

        lines = list(filter(lambda x: x[0] != "#", lines))

        lines = [l.strip() for l in lines]
        lines = [l[0:69] for l in lines]

        tles = sk.TLE.from_lines(lines)
        for tle in tles:
            fname = f"{basedir}{os.path.sep}{tle.satnum:05}.e"
            with open(fname, "r") as fh:
                testvecs = fh.readlines()
            for testvec in testvecs:
                stringvals = testvec.split()

                # Valid lines are all floats of length 7
                if len(stringvals) != 7:
                    continue
                try:
                    vals = [float(s) for s in stringvals]
                except ValueError:
                    continue
                time = tle.epoch + sk.duration.from_seconds(vals[0])
                try:
                    [p, v, eflag] = sk.sgp4(  # type: ignore
                        tle,
                        time,
                        opsmode=sk.sgp4_opsmode.afspc,
                        gravconst=sk.sgp4_gravconst.wgs72,
                        errflag=True,
                    )

                    if eflag == sk.sgp4_error.success:
                        ptest = np.array([vals[1], vals[2], vals[3]]) * 1e3
                        vtest = np.array([vals[4], vals[5], vals[6]]) * 1e3
                        assert p == pytest.approx(ptest, rel=1e-4)
                        assert v == pytest.approx(vtest, rel=1e-2)
                    else:
                        # We know which one is supposed to fail in the test vectors
                        # Make sure we pick the correcxt one
                        assert tle.satnum == 33334
                        assert eflag == sk.sgp4_error.perturb_eccen
                except RuntimeError:
                    print("Caught runtime error; this is expected in test vectors")


class TestTLEMetadata:
    def test_tle_metadata_getters(self):
        """The catalog-identity fields must be readable (and settable)."""
        tle = sk.TLE.from_lines([ISS_NAME, *ISS_2021])[0]
        assert tle.intl_desig == "98067A"
        assert tle.desig_year == 98
        assert tle.desig_launch == 67
        assert tle.desig_piece == "A"
        assert tle.element_num == 900
        assert tle.rev_num == 29935
        assert tle.ephem_type == 0
        tle.element_num = 901
        assert tle.element_num == 901


class TestSGP4ListKwargs:
    def test_list_honors_gravconst(self):
        """The list path must honor gravconst/opsmode kwargs (previously
        silently ignored): list results must match per-TLE results computed
        with the same non-default settings."""
        tle_a = sk.TLE.from_lines(ISS_2021)[0]
        tle_b = sk.TLE.from_lines(ISS_2021)[0]
        t = tle_a.epoch + sk.duration.from_hours(6)

        p_single, v_single = sk.sgp4(tle_a, t, gravconst=sk.sgp4_gravconst.wgs84)
        p_list, v_list = sk.sgp4([tle_b], [t], gravconst=sk.sgp4_gravconst.wgs84)
        assert np.allclose(np.asarray(p_list).squeeze(), p_single)
        assert np.allclose(np.asarray(v_list).squeeze(), v_single)

        # And wgs84 must actually differ from the default wgs72
        p_72, _ = sk.sgp4(sk.TLE.from_lines(ISS_2021)[0], t)
        assert not np.allclose(p_72, p_single, rtol=0, atol=1e-3)


class TestSGP4XP:
    def test_type4_tle_rejected(self):
        """An SGP4-XP element set (ephemeris type 4) parses but cannot be propagated."""
        line1 = "1 00011U 59001A   23060.12028874 +.00002871  89876-2  73526-1 4 00010"
        line2 = "2 00011  32.8652 309.4507 1466152  63.9843 312.2337 11.85947359392148"
        tle = sk.TLE.from_lines([line1, line2])[0]
        assert tle.ephem_type == 4
        with pytest.raises(RuntimeError, match="SGP4-XP"):
            sk.sgp4(tle, tle.epoch)

    def test_type4_omm_rejected(self):
        """EPHEMERIS_TYPE 4 in an OMM is rejected the same way."""
        omm = {
            "OBJECT_NAME": "VANGUARD 1",
            "OBJECT_ID": "1958-002B",
            "EPOCH": "2023-03-01T02:53:12.947",
            "MEAN_MOTION": 10.84532081,
            "ECCENTRICITY": 0.1849434,
            "INCLINATION": 34.2437,
            "RA_OF_ASC_NODE": 69.7250,
            "ARG_OF_PERICENTER": 110.9844,
            "MEAN_ANOMALY": 271.4417,
            "EPHEMERIS_TYPE": 4,
            "NORAD_CAT_ID": 5,
        }
        with pytest.raises(RuntimeError, match="SGP4-XP"):
            sk.sgp4(omm, sk.time(2023, 3, 1, 3, 0, 0))


class TestTLELoaders:
    """TLE.from_lines / from_file always return a list and locate bad records."""

    def test_one_tle_is_a_list(self):
        tles = sk.TLE.from_lines([ISS_NAME, *ISS_2021])
        assert isinstance(tles, list)
        assert len(tles) == 1
        assert tles[0].name == "ISS (ZARYA)"

    def test_several_tles(self):
        tles = sk.TLE.from_lines([*ISS_2021, *STARLINK_3118])
        assert [t.satnum for t in tles] == [25544, 49140]

    def test_from_file_is_a_list(self, tmp_path):
        path = tmp_path / "one.tle"
        path.write_text("\n".join(STARLINK_3118) + "\n")
        tles = sk.TLE.from_file(str(path))
        assert isinstance(tles, list) and len(tles) == 1
        assert tles[0].satnum == 49140

    def test_zero_tles_raises(self, tmp_path):
        with pytest.raises(ValueError, match="No valid TLEs"):
            sk.TLE.from_lines([])
        with pytest.raises(ValueError, match="No valid TLEs"):
            sk.TLE.from_lines(["just a name", ""])
        path = tmp_path / "empty.tle"
        path.write_text("\n")
        with pytest.raises(ValueError, match="No valid TLEs"):
            sk.TLE.from_file(str(path))

    def test_error_names_line_and_satellite(self):
        # An 8-digit eccentricity shifts the rest of line 2 right by one
        shifted = STARLINK_3118[1].replace(" 0002663 ", " 00026630 ")
        assert len(shifted) == 70
        lines = [ISS_NAME, *ISS_2021, "", "0 SHIFTED", STARLINK_3118[0], shifted]
        with pytest.raises(RuntimeError) as exc:
            sk.TLE.from_lines(lines)
        msg = str(exc.value)
        assert "TLE record starting at line 5" in msg
        assert '49140 "SHIFTED"' in msg
        assert "mean anomaly" in msg
        assert "line 7 is 70 characters" in msg

    def test_check_checksum(self):
        # ISS_2021 has wrong checksums; STARLINK_3118 has correct ones
        assert len(sk.TLE.from_lines(ISS_2021)) == 1
        assert len(sk.TLE.from_lines(ISS_2021, check_checksum=False)) == 1
        assert len(sk.TLE.from_lines(STARLINK_3118, check_checksum=True)) == 1
        with pytest.raises(
            RuntimeError,
            match=r"starting at line 1 .*Line 1 checksum mismatch: column 69 is '3', but the line's checksum is 0",
        ):
            sk.TLE.from_lines(ISS_2021, check_checksum=True)

    def test_check_checksum_from_file(self, tmp_path):
        path = tmp_path / "bad.tle"
        path.write_text("\n".join([*STARLINK_3118, *ISS_2021]) + "\n")
        assert len(sk.TLE.from_file(str(path))) == 2
        with pytest.raises(RuntimeError, match="starting at line 3 .*checksum mismatch"):
            sk.TLE.from_file(str(path), check_checksum=True)

    def test_mismatched_line_pair_raises(self):
        # line 1 of the ISS with line 2 of a Starlink (a line lost from a file)
        with pytest.raises(RuntimeError, match="Satellite number differs"):
            sk.TLE.from_lines([ISS_2021[0], STARLINK_3118[1]])

    def test_orphan_line1_raises(self):
        # A line 1 followed by another record, or by the end of the input
        with pytest.raises(RuntimeError, match="line 1 .*Line 1 without a line 2"):
            sk.TLE.from_lines([ISS_2021[0], *STARLINK_3118])
        with pytest.raises(RuntimeError, match='line 3 .*"LOST".*Line 1 without a line 2'):
            sk.TLE.from_lines([*STARLINK_3118, "0 LOST", ISS_2021[0]])

    def test_short_line_hint(self):
        with pytest.raises(RuntimeError, match="looks like a line 1 but is 68 characters"):
            sk.TLE.from_lines([ISS_2021[0][:68], ISS_2021[1]])

    def test_check_checksum_is_keyword_only(self):
        with pytest.raises(TypeError):
            sk.TLE.from_lines(ISS_2021, True)  # type: ignore[misc]


class TestSGP4Cache:
    """The SGP4 initialization cached in a TLE never goes stale."""

    def test_setter_after_propagation(self):
        tle = sk.TLE.from_lines(ISS_2021)[0]
        tm = tle.epoch + sk.duration(minutes=90)
        sk.sgp4(tle, tm)
        tle.inclination = 97.0
        tle.mean_motion = 14.2
        fresh = sk.TLE.from_lines(ISS_2021)[0]
        fresh.inclination = 97.0
        fresh.mean_motion = 14.2
        assert np.array_equal(sk.sgp4(tle, tm)[0], sk.sgp4(fresh, tm)[0])

    def test_gravconst_after_propagation(self):
        tle = sk.TLE.from_lines(ISS_2021)[0]
        tm = tle.epoch + sk.duration(days=3)
        p72, _ = sk.sgp4(tle, tm)
        p84, _ = sk.sgp4(tle, tm, gravconst=sk.sgp4_gravconst.wgs84)
        p84_fresh, _ = sk.sgp4(sk.TLE.from_lines(ISS_2021)[0], tm, gravconst=sk.sgp4_gravconst.wgs84)
        assert np.array_equal(p84, p84_fresh)
        assert np.linalg.norm(p84 - p72) > 10.0
        # the same in the list form
        p84_list, _ = sk.sgp4([tle], tm, gravconst=sk.sgp4_gravconst.wgs84)
        assert np.array_equal(p84_list[0], p84_fresh)

    def test_equality_after_propagation(self):
        tle = sk.TLE.from_lines(ISS_2021)[0]
        copied = copy.deepcopy(tle)
        sk.sgp4(tle, tle.epoch)
        assert tle == copied
        assert tle == pickle.loads(pickle.dumps(tle))
        assert tle == sk.TLE.from_lines(ISS_2021)[0]

    def test_type4_after_propagation(self):
        tle = sk.TLE.from_lines(ISS_2021)[0]
        sk.sgp4(tle, tle.epoch)
        tle.ephem_type = 4
        with pytest.raises(RuntimeError, match="SGP4-XP"):
            sk.sgp4(tle, tle.epoch)


# An element set that fails SGP4 initialization (from the Vallado test set)
BAD_INIT = [
    "1 33334U 78066F   06174.85818871  .00000620  00000-0  10000-3 0  6809",
    "2 33334  68.4714 236.1303 5602877 123.7484 302.5767  0.00001000 67521",
]


class TestSGP4InitErrors:
    """How an element set that cannot be initialized is reported."""

    def test_list_with_errflag(self):
        good = sk.TLE.from_lines(ISS_2021)[0]
        bad = sk.TLE.from_lines(BAD_INIT)[0]
        xp = sk.TLE.from_lines(ISS_2021)[0]
        xp.ephem_type = 4
        times = [good.epoch, good.epoch + sk.duration(days=1)]
        p, v, err = sk.sgp4([good, bad, xp], times, errflag=True)
        assert p.shape == (3, 2, 3) and err.shape == (3, 2)
        assert np.all(err[0] == sk.sgp4_error.success)
        assert np.all(err[1] == sk.sgp4_error.perturb_eccen)
        assert np.all(err[2] == sk.sgp4_error.unsupported)
        assert np.all(np.isnan(p[1:])) and np.all(np.isnan(v[1:]))
        # the good element set is unaffected
        assert np.array_equal(p[0], sk.sgp4(good, times)[0])

    def test_list_without_errflag_raises(self):
        good = sk.TLE.from_lines(ISS_2021)[0]
        bad = sk.TLE.from_lines(BAD_INIT)[0]
        with pytest.raises(RuntimeError, match="element set 1 of the list"):
            sk.sgp4([good, bad], good.epoch)

    def test_single_matches_list(self):
        bad = sk.TLE.from_lines(BAD_INIT)[0]
        with pytest.raises(RuntimeError, match="SGP4 init error"):
            sk.sgp4(bad, bad.epoch)
        p, v, err = sk.sgp4(bad, bad.epoch, errflag=True)
        assert p.shape == (3,) and err.shape == (1,)
        assert np.all(np.isnan(p)) and err[0] == sk.sgp4_error.perturb_eccen
        assert int(sk.sgp4_error.unsupported) == 7

