#!/usr/bin/env python3
"""Generate the ``source:`` block of ``recipes/conda/satkit-data/recipe.yaml``
from ``data/manifest.json`` so the conda package never drifts from the data
that satkit itself pins.

Every entry points at the GitHub release asset (``manifest.release_base``)
with the manifest's SHA-256, extracted into ``data/``.

Usage::

    python tools/conda_sources_from_manifest.py            # print the block
    python tools/conda_sources_from_manifest.py --write    # rewrite recipe.yaml in place
    python tools/conda_sources_from_manifest.py --check    # exit 1 if recipe.yaml is stale

By default the block contains every manifest file except the full-span DE440
(``default: true`` ephemeris, 102 MB): the conda package ships the 14 MB DE421
to stay under conda-forge's 100 MB cap. Pass ``--with-de440`` to include it.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
MANIFEST = REPO / "data" / "manifest.json"
RECIPE = REPO / "recipes" / "conda" / "satkit-data" / "recipe.yaml"
BEGIN = "  # BEGIN generated by tools/conda_sources_from_manifest.py — do not edit by hand\n"
END = "  # END generated\n"


def selected(manifest: dict, with_de440: bool) -> list[dict]:
    files = []
    for f in manifest["files"]:
        if f.get("tier") == "ephemeris" and f.get("default", False) and not with_de440:
            continue  # DE440: too large for conda-forge; users can fetch it at runtime
        files.append(f)
    return files


def block(manifest: dict, with_de440: bool) -> str:
    base = manifest["release_base"].rstrip("/")
    out = [BEGIN, f"  # data_version: {manifest['data_version']}\n"]
    for f in selected(manifest, with_de440):
        out.append(f"  # {f['name']}: {f['source']} — {f.get('license', '')}\n")
        out.append(f"  - url: {base}/{f['name']}\n")
        out.append(f"    sha256: {f['sha256']}\n")
        out.append("    target_directory: data\n")
    out.append(END)
    return "".join(out)


def splice(recipe_text: str, new_block: str) -> str:
    pat = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END), re.S)
    if not pat.search(recipe_text):
        sys.exit(f"{RECIPE}: generated-block markers not found")
    return pat.sub(lambda _m: new_block, recipe_text, count=1)


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--write", action="store_true")
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--with-de440", action="store_true")
    a = ap.parse_args()
    manifest = json.loads(MANIFEST.read_text())
    new = block(manifest, a.with_de440)
    if a.write or a.check:
        text = RECIPE.read_text()
        updated = splice(text, new)
        if a.check:
            if updated != text:
                sys.exit(f"{RECIPE} is stale: run tools/conda_sources_from_manifest.py --write")
            print("recipe sources match data/manifest.json")
            return
        RECIPE.write_text(updated)
        print(f"wrote {RECIPE}")
    else:
        sys.stdout.write(new)


if __name__ == "__main__":
    main()
